-- CreateTable
CREATE TABLE "PaperRecord" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,
    "a4" DOUBLE PRECISION NOT NULL,
    "a5" DOUBLE PRECISION NOT NULL,
    "a6" DOUBLE PRECISION NOT NULL,
    "collegeblock" DOUBLE PRECISION NOT NULL,
    "zeichenmappe" DOUBLE PRECISION NOT NULL,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PaperRecord" ADD FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
